version: '3'

services:
  api:
    container_name: posts-api
    build: ./api
    restart: always
    ports:
     - 8000:8000
    volumes:
     - ./api:/api
    environment:
      API_SECRET: s3cr3t
      DATABASE_MODE: mysql
      MYSQL_HOSTNAME: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
    depends_on:
      - mysql

  mysql:
    container_name: posts-db
    image: mysql
    ports:
     - 3306:3306
    volumes:
     - .db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password

  web:
    container_name: posts-web
    build:
      context: ./web
      args:
        NODE_ENV: development
    restart: always
    ports:
     - "8080:80"
    depends_on:
      - api
