envName: prod
hostname: posts.k8s.sandbox.ggops.com

devEnvTtl: 7d

mysql:
  mysqlDatabase: posts
  mysqlUser: posts
  mysqlPassword: dbpassw0rd # use --set to override this in production

api:
  image:
    repository: mechtron/posts-api
    tag: 1.0.1
  serviceType: LoadBalancer
  apiSecret: apis3r3t # use --set to override this in production
  databaseMode: mysql
  djangoSuEmail: you@example.com
  djangoSuPassword: adminpassw0rd # use --set to override this in production
  debug: "true"

web:
  image:
    repository: mechtron/posts-web
    tag: 1.0.1
  serviceType: LoadBalancer
